HKSBossLCData = {
  ["Keeper Gnarlmoon"] = {
    ["Ley-attuned Choker"] = {"fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe"},
    ["Manadrenched Feather Slippers"] = {"fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe"},
    ["Torn Wings of Midnight"] = {"fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe"},
    ["Crite's Holy Hands"] = {"fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe"},
    ["Ravenkeeper's Frenzied Embrace"] = {"fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe"},
    ["Bloodmoon, Sickle of the Murderous Flight"] = {"fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe"},
    ["Idol of Laceration"] = {"fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe"},
    ["Crown of the Wildpack"] = {"fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe","fagrehe"},
  },
  ["Ley-Watcher Incantagos"] = {
    ["Magispark Leggings"] = {"dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa"},
    ["Jewel of Wild Magics"] = {"dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa"},
    ["Scaleshield of Azure Flight"] = {"dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa"},
    ["Loop of Infused Renewal"] = {"dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa"},
    ["Magehunter Belt"] = {"dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa"},
    ["Bands of the Surgebreaker"] = {"dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa"},
    ["Leysteel Legplates"] = {"dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa"},
    ["Choker of Terminal Arcanum"] = {"dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa"},
  },
  ["Anomalus"] = {
    ["Manahide Slippers"] = {"dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz"},
    ["Cloak of the Bloody Ravager"] = {"dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz"},
    ["Phase-shifting Crossbow"] = {"dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz"},
    ["Branch of Resolute Defense"] = {"dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz"},
    ["Remains of Overwhelming Power"] = {"dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz"},
    ["Choker of Chromatic Power"] = {"dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz"},
    ["Gloves of Nourishment"] = {"dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz"},
    ["Bindings of Contained Magic"] = {"dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz","dsadz"},
  },
  ["Echo of Medivh"] = {
    ["Medivh's Hindsight"] = {"dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad"},
    ["Gloves of Leyline Convergence"] = {"dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad"},
    ["Eye of Dormant Corruption"] = {"dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad"},
    ["Pendant of Forgiven Mistakes"] = {"dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad"},
    ["Dreadslayer Shoulderblades"] = {"dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad"},
    ["Legwraps of Meticulous Planning"] = {"dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad"},
    ["Libram of the Eternal Tower"] = {"dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad"},
    ["Forgotten Raven's Mallet"] = {"dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad","dsadsad"},
  },
  ["King"] = {
    ["Ethereal Boots of Conquest"] = {"rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt"},
    ["Ethereal Boots of Ascendancy"] = {"dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa"},
    ["Dragonclaw Gauntlets"] = {"dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa"},
    ["Checkmate"] = {"dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa"},
    ["King's Edict"] = {"dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa"},
    ["Insomnius' Retribution"] = {"dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa"},
    ["Royal Seal of Greymane"] = {"dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa"},
    ["Pawn's Advance"] = {"dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa"},
    ["Bishop's Reverence"] = {"dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa"},
    ["Chain-Cloak of the Rookguard"] = {"dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa","dwasdsa"},
  },
  ["Sanv Tas'dal"] = {
    ["Shifting Mantle of Conquest"] = {"rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt"},
    ["Shifting Mantle of Ascendancy"] = {"dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa"},
    ["Dreadslayer Horns"] = {"dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas"},
    ["Totem of Broken Earth"] = {"dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas"},
    ["Riftcarver's Implement"] = {"dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas"},
    ["Raka'shishi, Spear of the Adrift Hunt"] = {"dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas"},
    ["Kum'isha's Tattered Drape"] = {"dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas"},
    ["Forgotten Hide Helm"] = {"dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas"},
    ["Girdle of the Faded Primals"] = {"dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas"},
  },
  ["Rupturan the Broken"] = {
    ["Fractured Crown of Conquest"] = {"rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt"},
    ["Fractured Crown of Ascendancy"] = {"dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa"},
    ["Bulwark of Enduring Earth"] = {"dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa"},
    ["Earthquake Leggings"] = {"dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa"},
    ["Loop of Hardened Slate"] = {"dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa"},
    ["Pure Jewel of Draenor"] = {"dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa"},
    ["Handwraps of Dead Winds"] = {"dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa"},
    ["Mantle of the Drifting Stars"] = {"dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa"},
    ["Al'Kazeth, Claw of Ruptured Elements"] = {"dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa","dsadsadsa"},
  },
  ["Kruul"] = {
    ["Brutal Leggings of Conquest"] = {"rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt"},
    ["Brutal Leggings of Ascendancy"] = {"dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa"},
    ["Hellflame"] = {"dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas"},
    ["Shar'tateth, the Shattered Edge"] = {"dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas"},
    ["Comet Signaller"] = {"dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas"},
    ["Desecration"] = {"dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas"},
    ["Wristwraps of Exiled Radiance"] = {"dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas"},
    ["Shieldrender Talisman"] = {"dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas"},
    ["Pendant of Purified Demon's Blood"] = {"dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas","dsadas"},
  },
  ["Mephistroth"] = {
    ["Nathrezim Armor of Treachery"] = {"rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt","rteqt"},
    ["Nathrezim Armor of Deceit"] = {"dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa","dasdasdsa"},
    ["Heart of Mephistroth"] = {"dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa"},
    ["Turalyon's Hope"] = {"dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa"},
    ["Cloak of Rapid Regeneration"] = {"dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa"},
    ["Mephistroth's Cunning"] = {"dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa"},
    ["Khadgar's Guidance"] = {"dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa"},
    ["Memory of the Last Guardian"] = {"dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa"},
    ["Netherwrought Bracers"] = {"dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa"},
    ["Sash of the Grand Betrayal"] = {"dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa"},
    ["Forgotten Hide Pauldrons"] = {"dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa"},
    ["Tunic of Demonic Deception"] = {"dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa","dsadasdsa"},
    ["Rain of Spiders"] = {"dewatwa","dewatwa","dewatwa","dewatwa","dewatwa","dewatwa"},
    ["Thunderfall, Stormhammer of the Chief Thane"] = {"dewatwa","dewatwa","dewatwa","dewatwa","dewatwa","dewatwa"},
    ["Kirel'narak, the Death Sentence"] = {"dewatwa","dewatwa","dewatwa","dewatwa","dewatwa","dewatwa"},
    ["Nethraka, Wing of Oblivion"] = {"dewatwa","dewatwa","dewatwa","dewatwa","dewatwa","dewatwa"},
    ["Censer of Soulwarding"] = {"dewatwa","dewatwa","dewatwa","dewatwa","dewatwa","dewatwa"},
  },
  ["Wastewander Bandit"] = {
    ["Wastewander Water Pouch"] = {"Ninjaekorn","Ninjamagic","Thornton","Someone", "Scooby", "dsadasdsadsasdasdsa","dasdasdz"},
	["Mageweave Cloth"] = {"Ninjaekorn","Ninjamagic","Thornton","Someone", "Scooby", "dsadasdsadsasdasdsa","dasdasdz"},
	["Silk Cloth"] = {"Ninjaekorn","Ninjamagic","Thornton","Someone", "Scooby", "dsadasdsadsasdasdsa","dasdasdz"},
	["Pattern: Tough Scorpid Breastplate"] = {"Ninjaekorn","Ninjamagic","Thornton","Someone", "Scooby", "dsadasdsadsasdasdsa","dasdasdz"},
  },
  ["Wastewander Thief"] = {
    ["Wastewander Water Pouch"] = {"Ninjaekorn","Ninjamagic","Thornton","Someone", "Scooby", "dsadasdsadsasdasdsa","dasdasdz"},
	["Mageweave Cloth"] = {"Ninjaekorn","Ninjamagic","Thornton","Someone", "Scooby", "dsadasdsadsasdasdsa","dasdasdz"},
	["Silk Cloth"] = {"Ninjaekorn","Ninjamagic","Thornton","Someone", "Scooby", "dsadasdsadsasdasdsa","dasdasdz"},
	["Greater Mana Potion"] = {"Ninjaekorn","Ninjamagic","Thornton","Someone", "Scooby", "dsadasdsadsasdasdsa","dasdasdz"},
	["Pattern: Tough Scorpid Breastplate"] = {"Ninjaekorn","Ninjamagic","Thornton","Someone", "Scooby", "dsadasdsadsasdasdsa","dasdasdz"},
	["Pattern: Tough Scorpid Gloves"] = {"Ninjaekorn","Ninjamagic","Thornton","Someone", "Scooby", "dsadasdsadsasdasdsa","dasdasdz"},
	["Greenstone Circle of the Gorilla"] = {"Ninjaekorn","Ninjamagic","Thornton","Someone", "Scooby", "dsadasdsadsasdasdsa","dasdasdz"},
  },
  --[["Scorpid Hunter"] = {
    ["Broken Scorpid Leg"] = {"Ninjaekorn","Ninjamagic","Thornton","Someone", "Scooby", "dsadasdsadsasdasdsa","dasdasdz"},
	["Mystery Meat"] = {"Billy","Ninjamagic","Thornton","Someone", "Scooby", "dsadasdsadsasdasdsa","dasdasdz"},
	["Empty Venom Sac"] = {"Ninjaekorn","Ninjamagic","Thornton","Someone", "Scooby", "dsadasdsadsasdasdsa","dasdasdz"},
	["Small Scorpid Claw"] = {"Billy","Bob","Ninjamagic","Someone", "Scooby", "dsadasdsadsasdasdsa","dasdasdz"},
	["Greater Mana Potion"] = {"Ninjaekorn","Ninjamagic","Thornton","Someone", "Scooby", "dsadasdsadsasdasdsa","dasdasdz"},
  },]]
}

HKSTierNeckLCData = {
  ["Ephemeral Pendant"] = {"Ninjaekornet","Supairisu","Scoobydoo","Shaggyboy", "Daphnegirl", "Daphnegirl2","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz","dasdasdz"},
}

HKSTrashLootLCData = {
  ["Slivers of Nullification"] = {"dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa"},
  ["The End of All Ambitions"] = {"dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa"},
  ["Ques' Gauntlets of Precision"] = {"dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa"},
  ["Boots of Elemental Fury"] = {"dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa"},
  ["Gauntlets of Elemental Fury"] = {"dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa"},
  ["Boots of the Grand Crusader"] = {"dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa"},
  ["Gauntlets of the Grand Crusader"] = {"dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa"},
  ["Dragunovi's Sash of Domination"] = {"dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa"},
  ["Ring of Holy Light"] = {"dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa"},
  ["Brand of Karazhan"] = {"dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa","dsadsa"},
    ["Broken Scorpid Leg"] = {"Ninjaekorn","Ninjamagic","Thornton","Someone", "Scooby", "dsadasdsadsasdasdsa","dasdasdz"},
	["Mystery Meat"] = {"Billy","Ninjamagic","Ninjaekorn","Someone", "Scooby", "dsadasdsadsasdasdsa","dasdasdz"},
	["Empty Venom Sac"] = {"Ninjaekorn","Ninjamagic","Thornton","Someone", "Scooby", "dsadasdsadsasdasdsa","dasdasdz"},
	["Small Scorpid Claw"] = {"Ninjaekorn","Bob","Ninjamagic","Someone", "Scooby", "dsadasdsadsasdasdsa","dasdasdz"},
	["Greater Mana Potion"] = {"Ninjaekorn","Ninjamagic","Thornton","Someone", "Scooby", "dsadasdsadsasdasdsa","dasdasdz"},
}